
find_path(MOSQUITTO_INCLUDE_DIR NAMES mosquitto.h)

find_library(MOSQUITTO_LIBRARY NAMES mosquitto)

if (MOSQUITTO_LIBRARY)
    get_filename_component (MOSQUITTO_LIBRARY_DIR ${MOSQUITTO_LIBRARY} DIRECTORY)
endif ()

find_package(PackageHandleStandardArgs REQUIRED)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MOSQUITTO REQUIRED_VARS 
    MOSQUITTO_INCLUDE_DIR MOSQUITTO_LIBRARY MOSQUITTO_LIBRARY_DIR)

if(MOSQUITTO_FOUND)
  set(MOSQUITTO_LIBRARIES ${MOSQUITTO_LIBRARY})
  set(MOSQUITTO_INCLUDE_DIRS ${MOSQUITTO_INCLUDE_DIR})
  set(MOSQUITTO_LIBRARY_DIRS ${MOSQUITTO_LIBRARY_DIR})
endif()

